const fs=require('node:fs');
const path=require('node:path');
const M=require('../lib/document-structured-extraction');
const D=require('../lib/scan-process-deadline');
function walk(d,out){for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f,out);else if(e.name==='documents.json')out.push(f);}}
function num(d){if(d.type==='quote')return d.quoteNumber;if(d.type==='order')return d.orderNumber;return d.invoiceNumber;}
function snap(d){return {number:num(d),customer:d.customerName,itemCount:Array.isArray(d.items)?d.items.length:0,subtotal:d.subtotal,vat:d.vatAmount,total:d.total,currency:d.currency};}
function empty(v){return v===undefined||v===null||v==='';}
function same(a,b){if(typeof a==='number'&&typeof b==='number')return Math.abs(a-b)<0.011;return String(a??'').trim()===String(b??'').trim();}
async function main(){const files=[];walk('test-data',files);let total=0,replayable=0,skipped=0,sameCount=0,changed=0,loss=0,errors=0;const rows=[];for(const file of files){let docs;try{docs=JSON.parse(fs.readFileSync(file,'utf8'));}catch(e){continue;}if(!Array.isArray(docs))continue;for(const doc of docs){total++;const pages=doc.structuredExtraction&&Array.isArray(doc.structuredExtraction.pages)?doc.structuredExtraction.pages:[];if(!pages.length){skipped++;continue;}replayable++;try{const inputs=pages.map(function(p){return {pageIndex:p.pageIndex,lines:(p.lines||[]).map(function(l){const x={text:l.text,confidence:0.9};if(l.boundingBox)x.boundingBox=l.boundingBox;if(l.elements)x.elements=l.elements;return x;}),rawText:(p.lines||[]).map(function(l){return l.text;}).join('\n'),width:p.width,height:p.height};});const ex=await M.extractStructuredDocumentAsync(doc.type,inputs,{processDeadline:D.createScanProcessDeadline(inputs.length)});const applied=M.applyStructuredExtractionToDocument(Object.assign({},doc,{items:doc.items||[]}),ex,{mode:'new_scan'});const before=snap(doc),after=snap(applied);const diffs=[];const losses=[];for(const k of Object.keys(before)){if(!empty(before[k])&&!same(before[k],after[k])){diffs.push({field:k,before:before[k],after:after[k]});if(empty(after[k])||(k==='itemCount'&&before[k]!==0&&after[k]===0))losses.push(k);}}if(losses.length){loss++;rows.push({status:'LOSS',file,id:doc.id,type:doc.type,losses,diffs});}else if(diffs.length){changed++;rows.push({status:'CHANGED',file,id:doc.id,type:doc.type,diffs});}else{sameCount++;}if(replayable%10===0)console.log('REPLAY '+replayable);}catch(e){errors++;rows.push({status:'ERROR',file,id:doc.id,type:doc.type,error:String(e&&e.stack||e)});}}}const summary={documentRows:total,replayable,notReplayable:skipped,same:sameCount,changed,loss,errors};fs.writeFileSync('historical_regression_report.json',JSON.stringify({summary,rows},null,2));console.log('\nSUMMARY');console.log(JSON.stringify(summary,null,2));}
main().catch(function(e){console.error(e);process.exitCode=1;});